# Generated by Django 4.2.16 on 2024-11-16 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('race_type', models.CharField(choices=[('Sprint', 'Sprint'), ('Obstacle', 'Obstacle'), ('Endurance', 'Endurance')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chevaux/')),
            ],
        ),
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField(help_text='Expérience en années')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='jockeys/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('chevaux', models.ManyToManyField(related_name='courses', to='hippodrome.cheval')),
            ],
        ),
        migrations.AddField(
            model_name='cheval',
            name='jockey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hippodrome.jockey'),
        ),
    ]
