# Generated by Django 4.2.16 on 2024-11-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hippodrome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecurie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('max_chevaux', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Nettoyage', 'Nettoyage'), ('Soins Médicaux', 'Soins Médicaux'), ('Entraînement', 'Entraînement')], max_length=50)),
                ('cheval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hippodrome.cheval')),
            ],
        ),
        migrations.AddField(
            model_name='cheval',
            name='ecurie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chevaux', to='hippodrome.ecurie'),
        ),
    ]
