# Generated by Django 4.2.16 on 2024-11-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hippodrome', '0002_ecurie_zone_cheval_ecurie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecurie',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ecurie_logo/'),
        ),
        migrations.AddField(
            model_name='zone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_zone/'),
        ),
    ]
